apiVersion: v1
kind: ConfigMap
metadata:
  name: solidary-tech-config
  namespace: default
  labels:
    project: solidary-tech
    environment: production
data:
  # Endpoints gerados pela camada do Terraform
  DATABASE_HOST: "solidary-tech-db.us-east-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "solidary_db"
  DATABASE_USER: "solidary_admin"
  AWS_REGION: "us-east-1"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/123456789012/solidary-tech-donation-queue.fifo"

---
apiVersion: v1
kind: Secret
metadata:
  name: solidary-tech-secrets
  namespace: default
  labels:
    project: solidary-tech
    environment: production
type: Opaque
stringData:
  # Credenciais de acesso protegidas
  DATABASE_PASSWORD: "MudarSenhaForte123!"
