apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
  namespace: production
data:
  init.sql: |
    -- ====================================================
    -- SCRIPT DE INICIALIZAÇÃO DO BANCO RDS
    -- ====================================================
    CREATE TABLE IF NOT EXISTS ngos (id SERIAL PRIMARY KEY, name VARCHAR(255), email VARCHAR(255));
    CREATE TABLE IF NOT EXISTS donations (id SERIAL PRIMARY KEY, amount NUMERIC, ngo_id INT);
    CREATE TABLE IF NOT EXISTS volunteers (id SERIAL PRIMARY KEY, name VARCHAR(255), role VARCHAR(255));
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  namespace: production
spec:
  template:
    spec:
      containers:
      - name: postgres-client
        image: postgres:15-alpine
        command:
        - "sh"
        - "-c"
        - "psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f /data/init.sql"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASS
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER # <--- COLECIONADO DE BANDEJA: Mapeia o usuário real do Secret
        envFrom:
        - configMapRef:
            name: db-config
        volumeMounts:
        - name: sql-volume
          mountPath: /data
      volumes:
      - name: sql-volume
        configMap:
          name: db-init-sql
      restartPolicy: OnFailure
  backoffLimit: 2