apiVersion: apps/v1
kind: Deployment
metadata:
  name: solidary-tech-api
  namespace: production
  labels:
    app: solidary-tech-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solidary-tech-api
  template:
    metadata:
      labels:
        app: solidary-tech-api
    spec:
      containers:
      - name: api
        image: 396368123600.dkr.ecr.us-east-1.amazonaws.com/solidary-tech-api:latest # Ajuste para sua imagem se necessário
        ports:
        - containerPort: 3000 # Porta padrão da sua API (ajuste se for 5000, 8080, etc.)
        
        # 🔌 Injeta automaticamente tudo do ConfigMap e da Secret como Variáveis de Ambiente
        envFrom:
        - configMapRef:
            name: solidary-tech-config
        - secretRef:
            name: solidary-tech-secret

        # 💰 FinOps & Rightsizing: Recursos controlados para t3.medium
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        
        # 🎯 SRE & Confiabilidade: Probes de saúde da aplicação
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: solidary-tech-api-service
  namespace: production
spec:
  selector:
    app: solidary-tech-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
