apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: production
  labels:
    app: donation-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: donation-service
