apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donation-service-hpa
  namespace: default
  labels:
    app: donation-service
    project: solidary-tech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: donation-service # Alvo do escalonamento automático
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Escala se o uso médio de CPU passar de 70%
