apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solidary-tech-ingress
  namespace: production
  annotations:
    # 1. Indica que o ALB será voltado para a internet (público)
    alb.ingress.kubernetes.io/scheme: internet-facing

    # 2. Roteamento direto para o IP do Pod (Evita o hop extra do kube-proxy nos nós)
    alb.ingress.kubernetes.io/target-type: ip

    # 3. Define as portas de entrada que o ALB vai escutar
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

    # 4. Configura o Health Check padrão que o ALB vai usar para validar as APIs
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  # Crucial para o EKS saber qual controller deve assumir esse Ingress
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /api/donations
        pathType: Prefix
        backend:
          service:
            name: donation-service
            port:
              number: 8080
      - path: /api/ngos
        pathType: Prefix
        backend:
          service:
            name: ngo-service
            port:
              number: 8080
      - path: /api/volunteers
        pathType: Prefix
        backend:
          service:
            name: volunteer-service
            port:
              number: 8080