apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solidary-tech-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # 🟢 Captura o nome do microsserviço ($1) e o restante da rota ($2), limpando o prefixo '/api'
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/(ngos)(.*)
        pathType: ImplementationSpecific # 🟢 Necessário para o NGINX processar o Regex corretamente
        backend:
          service:
            name: ngo-service
            port:
              number: 3000

      - path: /api/(donations)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: donation-service
            port:
              number: 3000

      - path: /api/(volunteers)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: volunteer-service
            port:
              number: 3000