apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service
  namespace: production
  labels:
    app: volunteer-service
    project: solidary-tech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volunteer-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
        otel.com/collect: "true"
      labels:
        app: volunteer-service
    spec:
      containers:
      - name: volunteer-service
        image: 396368123600.dkr.ecr.us-east-1.amazonaws.com/volunteer-service:latest
        
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-credentials

        env:
        - name: DD_ENV
          value: "production"
        - name: DD_SERVICE
          value: "volunteer-service"
        - name: DD_VERSION
          value: "1.0.0"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: ENABLE_TELEMETRY
          value: "true"

        ports:
        - name: http
          containerPort: 5000

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: volunteer-service
  namespace: production
  labels:
    app: volunteer-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 5000
    protocol: TCP
  selector:
    app: volunteer-service
